---
- hosts: all
  name: Install Firefox web browser
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install Firefox web browser
      ansible.builtin.package:
        name: firefox-esr
