---
- name: Install Firefox web browser
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install Firefox web browser
      ansible.builtin.package:
        name: firefox-esr
