---
# Ensure all cloud-init services are enabled (in some distributions, they
# are not enabled by default).
- name: Enable all cloud-init services
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-init-local
        - cloud-init
        - cloud-config
        - cloud-final
