---
# Ensure all cloud-init services are enabled (in some distributions, they
# are not enabled by default).
- hosts: all
  name: Enable all cloud-init services
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-init-local
        - cloud-init
        - cloud-config
        - cloud-final
    # python3-yaml is required by the cloud-init Python script that
    # appends the necessary DHCP options to the Netplan configuration
    # created by cloud-init.
    - name: Install python3-pyyaml
      ansible.builtin.package:
        name:
          - python3-yaml
