---
- hosts: all
  name: Install UFW
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install UFW
      ansible.builtin.include_role:
        name: ufw
      vars:
        # Do not actually enforce firewall rules.  The user must turn
        # UFW on if they want it.
        ufw_state: disabled
